### ISSUE TITLE
Missing module after update to 3.0.3

### ISSUE THREAD

**Issue by cfs77** [carlowahlstedt/NewmanPostman_VSTS_Task#21]
Hi,

the task works fine before the last update.
The newman task now throws the following error.

2018-03-06T14:13:48.1211972Z ##[section]Starting: Newman - Postman
2018-03-06T14:13:48.1211972Z ==============================================================================
2018-03-06T14:13:48.1211972Z Task         : Newman the cli Companion for Postman
2018-03-06T14:13:48.1211972Z Description  : Using Newman, one can effortlessly run and test a Postman Collections directly from the command-line. Now in a task!
2018-03-06T14:13:48.1211972Z Version      : 3.0.3
2018-03-06T14:13:48.1211972Z Author       : Carlo Wahlstedt
2018-03-06T14:13:48.1211972Z Help         : [More Information](https://github.com/carlowahlstedt/NewmanPostman_VSTS_Task/blob/master/README.md)
2018-03-06T14:13:48.1211972Z ==============================================================================
2018-03-06T14:13:48.2774578Z module.js:471
2018-03-06T14:13:48.2774578Z     throw err;
2018-03-06T14:13:48.2774578Z     ^
2018-03-06T14:13:48.2774578Z 
2018-03-06T14:13:48.2774578Z Error: Cannot find module 'vsts-task-lib/task'
2018-03-06T14:13:48.2774578Z     at Function.Module._resolveFilename (module.js:469:15)
2018-03-06T14:13:48.2774578Z     at Function.Module._load (module.js:417:25)
2018-03-06T14:13:48.2774578Z     at Module.require (module.js:497:17)
2018-03-06T14:13:48.2774578Z     at require (internal/module.js:20:19)
2018-03-06T14:13:48.2774578Z     at Object.<anonymous> (E:\TFS-Build\vsts-agent-win7-x64-2.105.6\_work\_tasks\NewmanPostman_4e74f3b0-c5b7-48cf-970e-8d7071818557\3.0.3\newmantask.js:12:12)
2018-03-06T14:13:48.2774578Z     at Module._compile (module.js:570:32)
2018-03-06T14:13:48.2774578Z     at Object.Module._extensions..js (module.js:579:10)
2018-03-06T14:13:48.2774578Z     at Module.load (module.js:487:32)
2018-03-06T14:13:48.2774578Z     at tryModuleLoad (module.js:446:12)
2018-03-06T14:13:48.2774578Z     at Function.Module._load (module.js:438:3)
2018-03-06T14:13:48.3399492Z ##[error]Exit code 1 returned from process: file name 'E:\TFS-Build\vsts-agent-win7-x64-2.105.6\externals\node\bin\node.exe', arguments '"E:\TFS-Build\vsts-agent-win7-x64-2.105.6\_work\_tasks\NewmanPostman_4e74f3b0-c5b7-48cf-970e-8d7071818557\3.0.3\newmantask.js"'.
2018-03-06T14:13:48.3555746Z ##[section]Finishing: Newman - Postman

I tried to install the vsts-task-lib by myself. But it doesn't solve the problem.
Is this library a new requiment with version 3.0.3?

**Comment by carlowahlstedt** [comment]
hmm, probably not. We setup an CD pipeline in VSTS to get the task to the marketplace. My guess would be it missed that folder in the creation, but I'll have to look into it. We're trying to build up tests around the build/release, but we haven't gotten there yet.

Thanks, for the heads up. I'll get this fixed as soon as I can.

**Comment by carlowahlstedt** [comment]
@cfs77 you want to try it again? I just attempted to fix it.

**Comment by cfs77** [comment]
@carlowahlstedt: It works again! Thank you for fixing this bug. :-)

I have annother small problem with your task. I will create a new issue.
